---
- name: Install/update base packages
  apt:
    name: "{{ base_packages }}"
    state: latest
    update_cache: yes

- name: Include ufw for firewall configuration
  include_tasks: 'ufw.yml'

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

