---
- name: Install latest ufw version
  apt: package=ufw state=latest

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }

- name: Open and limit port for SSH on ufw
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  with_items:
    - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }

- name: Enable ufw logging
  ufw: logging=on

- name: Enable ufw
  ufw: state=enabled

- name: Ensure ufw service is running
  service:
    name: ufw
    state: started
